// <auto-generated />
using System;
using CalculadoraAhorrosApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculadoraAhorrosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260711045555_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("CalculadoraAhorrosApi.Entities.SimulationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("initial_amount");

                    b.Property<decimal>("InitialTaxYearly")
                        .HasColumnType("TEXT")
                        .HasColumnName("initial_tax_yearly");

                    b.Property<int>("PlazoDeAños")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalInterest")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("simulations");
                });
#pragma warning restore 612, 618
        }
    }
}
